#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="src/aiometer tests"

set -x

${PREFIX}black --check --diff --target-version=py36 --target-version=py37 --target-version=py38 --target-version=py39 $SOURCE_FILES
${PREFIX}flake8 $SOURCE_FILES
${PREFIX}mypy $SOURCE_FILES
${PREFIX}isort --check --diff $SOURCE_FILES
