#!/bin/sh -e

export PACKAGE="src/aiometer"

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'build' ] ; then
    rm -r build
fi

if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi

if [ -d "${PACKAGE}.egg-info" ] ; then
    rm -r ${PACKAGE}.egg-info
fi

find ${PACKAGE} -type f -name "*.py[co]" -delete
find ${PACKAGE} -type d -name __pycache__ -delete
