#!/bin/sh -e

VERSION_FILE="src/aiometer/__version__.py"
PREFIX=""
if [ -d "venv" ] ; then
    PREFIX="venv/bin/"
fi

if [ ! -z "$CI" ]; then 
    VERSION=$(grep __version__ ${VERSION_FILE} | grep -o '[0-9][^"]*')

    if [ "refs/tags/${VERSION}" != "${GIT_REF}" ] ; then
        echo "Git ref '${GIT_REF}' did not match package version '${VERSION}'"
        exit 1
    fi
fi

${PREFIX}twine upload "$@" dist/*
