trigger:
  - master

pr:
  - master

variables:
  CI: true
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

jobs:
  - job: Test
    strategy:
      matrix:
        Python37:
          pythonVersion: "3.7"
        Python38:
          pythonVersion: "3.8"

    steps:
      - template: templates/install.yml
        parameters:
          pythonVersion: $(pythonVersion)
      - script: scripts/check
        displayName: "Run checks"
      - script: scripts/test
        displayName: "Run tests"
      - script: |
          if [ $(pythonVersion) = '3.8' ] & [ -f .coverage ]; then
            python -m pip install codecov;
            codecov --required;
          fi
        env:
          CODECOV_TOKEN: $(codecovToken)
        displayName: "Upload coverage"
