resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: florimondmanca/azure-pipelines-templates
      ref: refs/tags/3.3

trigger:
  - master

pr:
  - master

variables:
  CI: true
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

jobs:
  - template: job--python-check.yml@templates
    parameters:
      pythonVersion: "3.9"

  - template: job--python-test.yml@templates
    parameters:
      jobs:
        py36: null
        py37: null
        py38: null
        py39:
          coverage: true
